const CL={quran:"Qur'an",stats:"Qur'an Statistics",prophets:"Prophets",hadith:"Hadith",seerah:"Seerah",fiqh:"Fiqh",arabic:"Arabic",history:"Islamic History",jannah:"Jannah & Jahannam",aqeedah:"Aqeedah",salah:"Salah",ramadan:"Ramadan",hajj:"Hajj",manners:"Islamic Manners"};
const TC=[["quran","stats"],["salah","fiqh","manners","ramadan"],["hajj","seerah","aqeedah"],["hadith","manners"],["arabic"],["jannah","prophets"],["history","fiqh"]];
const LET=[..."ابتثجحخدذرزسشصضطظعغفقكلمنهوي"];
const letters=(L,n)=>Array.from({length:n},(_,i)=>LET[(((L-1)*3)%28+i)%28]);
const CO=["#0e9f6e","#d97706","#2563eb","#db2777","#7c3aed","#0891b2","#dc2626"],tint=t=>` style="background:color-mix(in srgb,${CO[t]} 14%,var(--card));border-color:${CO[t]}66"`;
const lt=t=>`<svg viewBox="0 0 48 48"><text x="24" y="35" text-anchor="middle" style="fill:${CO[t]};font-weight:700" font-size="32" font-family="'Amiri','Noto Naskh Arabic','Scheherazade New',serif">${G.lt[t]}</text></svg>`;
const BG=[["First Knowledge","Answer your first question correctly",()=>S.c>0],["Qur'an Seeker","10 correct Qur'an answers",()=>cc("quran")+cc("stats")>=10],["Hadith Student","8 correct Hadith answers",()=>cc("hadith")>=8],["Seerah Explorer","5 correct Seerah answers",()=>cc("seerah")>=5],["Arabic Learner","5 correct Arabic answers",()=>cc("arabic")>=5],["Knowledge Seeker","Earn 10,000 points",()=>S.kp>=10000],["Consistent Student","7-day streak",()=>S.st>=7]];
let S;try{S=JSON.parse(localStorage.getItem("ilmq"))}catch(e){}S=Object.assign({kp:0,st:0,last:"",a:0,c:0,cs:{},mx:1,b:[],seen:[],learn:[],d:[],pi:[],m:false},S||{});
const save=()=>{try{localStorage.setItem("ilmq",JSON.stringify(S))}catch(e){}};
const $=i=>document.getElementById(i),cc=k=>(S.cs[k]||[0,0])[1],today=()=>new Date().toISOString().slice(0,10),plv=()=>Math.floor(S.kp/500)+1,fmt=s=>String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0");
const phOf=L=>Math.floor((L-1)/LPP),nxt=()=>Math.min(S.mx,TOTAL),plab=L=>"Phase "+(phOf(L)+1)+" • Level "+L;
function show(id){["home","ph","lvs","gm","pf"].forEach(x=>$(x).hidden=x!=id);$("scene").hidden=id!="home";if(id=="home"){$("scene").innerHTML=scene(phOf(nxt()));$("cont").innerHTML=`<button class="cta" onclick="go(nxt())"><small>CONTINUE</small>Level ${nxt()}</button><div style="text-align:center"><span class="chip">${plab(nxt())} · ${PHASES[phOf(nxt())].name}</span></div>`}if(id=="ph")phases()}
function phases(){const cur=phOf(nxt());$("ph").innerHTML=`<div class="top"><button onclick="show('home')">‹</button><b>Phases</b><span></span></div>`+PHASES.map((p,i)=>{const st=i<cur?"Completed":i==cur?"Current · Level "+nxt():"Locked";return`<button class="b" ${i>cur?"disabled style='opacity:.4'":""} onclick="openPhase(${i})"><span class="m">Phase ${i+1} · ${st}</span><br>${p.name}</button>`}).join("")}
function openPhase(p){show("lvs");$("lt").textContent="Phase "+(p+1)+" · "+PHASES[p].name;$("lg").innerHTML="";for(let i=p*LPP+1;i<=Math.min((p+1)*LPP,TOTAL);i++){const b=document.createElement("button");b.textContent=i;b.disabled=i>S.mx;b.onclick=()=>go(i);$("lg").appendChild(b)}}
function go(L){const p=phOf(L);if(L==p*LPP+1&&!S.pi.includes(p)){if(p>0)A.say("phase");$("ovl").innerHTML=`<div class="ov"><div class="card" style="text-align:center">${p>0?"<p><b>Mā shā' Allāh!</b> A new chapter of your journey has begun.</p>":""}<div class="cat" style="justify-content:center">Phase ${p+1}</div><h2 style="color:var(--ac)">${PHASES[p].name.toUpperCase()}</h2><p>${PHASES[p].intro}</p><button class="b p" id="bg">Begin</button></div></div>`;$("bg").onclick=()=>{S.pi.push(p);save();$("ovl").innerHTML="";start(L)}}else start(L)}
function beep(f,d=.12){if(S.m||!A.fx())return;try{const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.04;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d)}catch(e){}}
function toast(t){const e=document.createElement("div");e.className="card note";e.style.cssText="position:fixed;top:12px;left:12px;right:12px;z-index:1100;margin:auto";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2600)}
// ---- questions: never repeat until every question in the pool has been seen
// Each level owns a fixed set of LQN questions: no question belongs to two levels. Easy first, fields interleaved, so difficulty rises with the level.
const LQN=4;let LQ=null;
let RES=[];
function lq(L){if(!LQ){const rk={easy:0,medium:1,hard:2},cs=Object.keys(CL),ord=[];[0,1,2].forEach(r=>{const b=cs.map(c=>Q.map((q,i)=>i).filter(i=>!Q[i][7]&&Q[i][0]==c&&(rk[Q[i][1]]??2)==r));while(b.some(x=>x.length))b.forEach(x=>{if(x.length)ord.push(x.shift())})});
// Build each level's group: 4 questions with different fields AND different answers, easiest first.
LQ=[];while(ord.length){const g=[];for(let k=0;k<ord.length&&g.length<LQN;k++){const i=ord[k];if(!g.some(j=>Q[j][0]==Q[i][0]||Q[j][3][0]==Q[i][3][0]))g.push(i)}if(!g.length)g.push(ord[0]);g.forEach(i=>ord.splice(ord.indexOf(i),1));LQ.push(...g)}
const as=new Set(LQ.slice(0,TOTAL*LQN));RES=Q.map((q,i)=>i).filter(i=>!Q[i][7]&&!as.has(i))}
// A question already seen (earlier play, a retry or a replay) is swapped for an unseen reserve question of the same field.
const used=new Set(),out=[];LQ.slice((L-1)*LQN,L*LQN).forEach(i=>{let r=i;if(S.seen.includes(i)){const f=RES.filter(j=>!S.seen.includes(j)&&!used.has(j)),s=f.filter(j=>Q[j][0]==Q[i][0]),p=s.length?s:f;if(p.length)r=p[Math.random()*p.length|0]}used.add(r);out.push(r)});return out}
// Daily Ilm: 10 questions you have not seen yet (reserve first), spread across as many fields as possible.
function dailyIds(sr){lq(1);const rs=new Set(RES),lv=Q.map((q,i)=>i).filter(i=>!Q[i][7]),un=lv.filter(i=>!S.seen.includes(i)),ur=un.filter(i=>rs.has(i)),pool=sr(ur.length>=10?ur:un.length>=10?un:lv),ids=[],cs=new Set();pool.forEach(i=>{if(ids.length<10&&!cs.has(Q[i][0])){cs.add(Q[i][0]);ids.push(i)}});pool.forEach(i=>{if(ids.length<10&&!ids.includes(i))ids.push(i)});return ids}
const QM=(n,M)=>{let p=0;return Array.from({length:n},(_,k)=>p=Math.max(p+1,Math.round(M*(k+1)/(n+1))))};
function pick(cats){const un=Q.map((q,i)=>i).filter(i=>!S.seen.includes(i));if(!un.length){S.seen=[];return pick(cats)}const pr=un.filter(i=>cats.includes(Q[i][0])),p=pr.length?pr:un;return p[Math.random()*p.length|0]}
function ask(i,mult,cb){if(!S.seen.includes(i))S.seen.push(i);const q=Q[i],o=Eng.sh(q[3].map((t,k)=>[t,k==0]));
$("ovl").innerHTML=`<div class="ov"><div class="card"><div class="cat"><span>${CL[q[0]]}</span><span id="dt"></span></div><h3>${q[2]}</h3>${q[6]=="d"?'<div class="note">Scholars or counting methods differ here; the commonly cited position is used.</div>':""}<div id="qo"></div><div id="qr"></div></div></div>`;
o.forEach(([t,ok])=>{const b=document.createElement("button");b.className="o";b.textContent=t;b.onclick=()=>{[...$("qo").children].forEach((x,k)=>{x.disabled=true;if(o[k][1])x.classList.add("ok")});if(!ok)b.classList.add("no");
const c=S.cs[q[0]]=S.cs[q[0]]||[0,0];S.a++;c[0]++;let p=0;if(ok){S.c++;c[1]++;p=(S.learn.includes(i)&&mult==1)?0:100*mult;S.kp+=p;if(G)G.sc+=p;if(!S.learn.includes(i))S.learn.push(i);beep(880)}else beep(180,.3);
$("qr").innerHTML=`<p><b>${ok?(p?"Correct · +"+p+" Knowledge Points":"Correct"):"Not quite"}</b><br>${q[4]}</p><button class="b" onclick="this.nextSibling.hidden=!this.nextSibling.hidden">How do we know?</button><div class="note" hidden><b>${q[6]=="d"?"Scholarly difference":"Verified"}</b><br>${q[5]}</div><button class="b p" id="nx">Continue</button>`;
$("nx").onclick=()=>{$("ovl").innerHTML="";badges();save();cb(ok)}};$("qo").appendChild(b)})}
function badges(){BG.forEach(([n,d,f])=>{if(!S.b.includes(n)&&f()){S.b.push(n);beep(1100,.4);A.say("badge");toast("Badge earned: "+n)}})}
// ---- game
let G=null,tm;
function start(L,keep){clearInterval(tm);const g=Eng.gen(L);G={L,qs:lq(L),qm:QM(lq(L).length,g.tiles.length/3),lt:letters(L,g.ty),b:g.tiles,tr:[],h:[],sc:0,cb:0,m:0,lv:keep??3,u:3,s:2,hi:2,time:g.time,lock:false,hl:null,out:-1};show("gm");draw();
tm=setInterval(()=>{if(G.lock)return;G.time--;draw();if(G.time<=0)lose("Time is up")},1000)}
function draw(){$("gl").textContent="Level "+G.L;$("gs").textContent="★ "+G.sc;$("gt").textContent=fmt(Math.max(G.time,0));$("gv").textContent="♥ ".repeat(G.lv).trim();
$("bu").textContent="Undo "+G.u;$("bs").textContent="Shuffle "+G.s;$("bh").textContent="Hint "+G.hi;
$("tray").innerHTML=Array.from({length:7},(_,i)=>G.tr[i]?`<div class="tt${G.tr[i].t==G.out?" out":""}"${tint(G.tr[i].t)}>${lt(G.tr[i].t)}</div>`:'<div class="s"></div>').join("");
const all=G.b,W=Math.max(...all.map(t=>t.x))+1,H=Math.max(...all.map(t=>t.y))+1,bd=$("bd");bd.style.cssText=`aspect-ratio:${W}/${H};width:min(100%,${(62*W/H).toFixed(1)}vh)`;
bd.innerHTML=all.map(t=>`<button class="t${Eng.free(all,t)?"":" bl"}${G.hl==t.id?" h":""}" style="left:${t.x/W*100}%;top:${t.y/H*100}%;width:${100/W}%;height:${100/H}%;z-index:${t.z*20+Math.round(t.y)}" onclick="tap(${t.id})"><i${Eng.free(all,t)?tint(t.t):""}>${lt(t.t)}</i></button>`).join("")}
function tap(id){if(G.lock)return;const x=G.b.find(t=>t.id==id);if(!x||!Eng.free(G.b,x))return;G.b=G.b.filter(t=>t!=x);G.h.push(x);G.hl=null;beep(520,.05);
const at=G.tr.map(y=>y.t).lastIndexOf(x.t);at<0?G.tr.push(x):G.tr.splice(at+1,0,x);draw();
if(G.tr.filter(y=>y.t==x.t).length==3){G.lock=true;G.out=x.t;draw();setTimeout(()=>{G.tr=G.tr.filter(y=>y.t!=x.t);G.h=G.h.filter(y=>y.t!=x.t);G.out=-1;G.cb++;G.m++;const p=10*G.cb;G.sc+=p;S.kp+=p;beep(700);draw();
const done=()=>{G.lock=false;if(!G.b.length&&!G.tr.length)win();else draw();save()};
const qk=G.qm.indexOf(G.m);if(qk>=0)ask(G.qs[qk],1,ok=>{if(!ok)G.cb=0;done()});else done()},280)}
else if(G.tr.length>=7)lose("The tray is full")}
function undo(){if(G.lock||!G.u||!G.h.length)return;const x=G.h.pop();G.tr=G.tr.filter(y=>y!=x);G.b.push(x);G.u--;G.hl=null;draw()}
function shuf(){if(G.lock||!G.s||G.b.length<2)return;Eng.reshuffle(G.b,G.tr);G.s--;G.hl=null;draw()}
function hint(){if(G.lock||!G.hi||!G.b.length)return;const f=G.b.filter(t=>Eng.free(G.b,t)),tt=G.tr.map(y=>y.t),t=f.find(x=>tt.includes(x.t))||f[0];G.hl=t.id;G.hi--;draw()}
function lose(m){clearInterval(tm);G.lock=true;G.lv--;const L=G.L,v=G.lv;beep(150,.4);$("ovl").innerHTML=`<div class="ov"><div class="card"><h3>${m}</h3><p class="m">${v?v+" ♥ remaining":"No lives left"}</p><button class="b p" id="rt">${v?"Try again":"Back to levels"}</button></div></div>`;$("rt").onclick=()=>{$("ovl").innerHTML="";v?start(L,v):openPhase(phOf(L))}}
const SC={kaaba:'<rect x="75" y="26" width="50" height="46" fill="#222"/><rect x="75" y="37" width="50" height="6" fill="var(--gold)"/><rect x="92" y="50" width="10" height="22" fill="var(--gold)"/>',
mosque:'<rect x="55" y="48" width="80" height="24" fill="var(--ac)"/><path d="M65 48a30 28 0 0 1 60 0z" fill="var(--ac)"/><rect x="145" y="24" width="9" height="48" fill="var(--ac)"/><path d="M144 24l5.5-11 5.5 11z" fill="var(--gold)"/><circle cx="95" cy="18" r="3" fill="var(--gold)"/>',
dome:'<path d="M70 72V52h60v20z" fill="#2f80c4"/><path d="M74 52a26 26 0 0 1 52 0z" fill="var(--gold)"/><rect x="99" y="18" width="2" height="8" fill="var(--gold)"/>',
mountain:'<path d="M15 72L72 22l42 50z" fill="#8b7d6b"/><path d="M80 72l48-42 56 42z" fill="#a39482"/>',
cave:'<path d="M30 72L100 15l70 57z" fill="#8b7d6b"/><path d="M85 72V58a15 15 0 0 1 30 0v14z" fill="#1c1c1c"/>',
sea:'<rect y="40" width="200" height="50" fill="#2f80c4"/><path d="M0 54q12-8 25 0t25 0 25 0 25 0 25 0 25 0 25 0M0 70q12-8 25 0t25 0 25 0 25 0 25 0 25 0 25 0" stroke="#fff" stroke-width="2" fill="none" opacity=".6"/>',
river:'<path d="M0 88C60 72 90 62 112 46S170 22 200 14V90H0z" fill="#2f80c4"/><path d="M30 72V48M30 48q-12-7-17-2M30 48q12-7 17-2" stroke="var(--ac)" stroke-width="3" fill="none"/>',
city:'<rect x="18" y="46" width="26" height="26" fill="var(--ac)"/><rect x="50" y="34" width="22" height="38" fill="var(--ac)"/><rect x="128" y="40" width="26" height="32" fill="var(--ac)"/><rect x="160" y="50" width="22" height="22" fill="var(--ac)"/><path d="M78 72V54h42v18zM82 54a17 15 0 0 1 34 0z" fill="var(--gold)"/>',
school:'<path d="M38 72V42l62-24 62 24v30z" fill="var(--ac)"/><rect x="62" y="48" width="9" height="24" fill="var(--card)"/><rect x="96" y="48" width="9" height="24" fill="var(--card)"/><rect x="130" y="48" width="9" height="24" fill="var(--card)"/>',
well:'<rect x="76" y="42" width="48" height="30" fill="#8a8a85"/><ellipse cx="100" cy="42" rx="24" ry="8" fill="#6e6e69"/><ellipse cx="100" cy="42" rx="18" ry="5" fill="#2f80c4"/>',
plain:'<circle cx="160" cy="24" r="10" fill="var(--gold)"/><path d="M20 72l18-24 18 24zM62 72l18-24 18 24zM104 72l18-24 18 24z" fill="var(--card)" stroke="var(--gold)" stroke-width="1.5"/>'};
const pic=id=>`<svg viewBox="0 0 200 90" style="width:100%;border-radius:10px;display:block" stroke="none"><rect width="200" height="90" fill="var(--dim)"/><rect y="72" width="200" height="18" fill="var(--bd)"/>${SC[ART[id]]||SC.city}</svg><div class="m" style="font-size:11px;text-align:right;margin-bottom:4px">Illustration</div>`;
function pcard(p){return pic(p.id)+`<div class="cat"><span>${p.category}</span><span>${p.basis.join(" · ")}</span></div><h3 style="margin:6px 0 2px">${p.name.toUpperCase()}</h3><div class="m">${p.location}</div><p>${p.description}</p>${(FACTS[p.id]||[]).length?`<div class="cat" style="margin:8px 0 2px">Did you know</div><ul style="margin:4px 0;padding-left:18px;font-size:14px">${FACTS[p.id].map(f=>`<li>${f}</li>`).join("")}</ul>`:""}<button class="b" onclick="this.nextSibling.hidden=!this.nextSibling.hidden">Learn More</button><div class="note" hidden>${p.quranReference?"<b>Qur'an:</b> "+p.quranReference+"<br>":""}${p.hadithReference?"<b>Hadith:</b> "+p.hadithReference+"<br>":""}${p.historicalReference?"<b>History:</b> "+p.historicalReference+"<br>":""}<b>${p.verification=="scholarly_difference"?"Scholars or sources differ on part of this":"Verified"}</b></div>`}
function win(){clearInterval(tm);const L=G.L,bonus=50*L,p=PLACES[L-1];S.kp+=bonus;G.sc+=bonus;S.mx=Math.min(Math.max(S.mx,L+1),TOTAL);if(p&&!S.d.includes(p.id))S.d.push(p.id);badges();save();beep(1000,.5);A.say("level");
const end=L>=TOTAL;$("ovl").innerHTML=`<div class="ov"><div class="card"><h3>Level ${L} complete</h3><p><b>Mā shā' Allāh!</b> You passed.</p><p class="m">+${bonus} Knowledge Points · ★ ${G.sc}</p>${p?`<hr style="border:0;border-top:1px solid var(--bd)"><div class="cat" style="margin:10px 0">Discover</div>${pcard(p)}`:""}<button class="b p" id="nl">${end?"Phases":"Continue"}</button><button class="b" id="bk">Home</button></div></div>`;
$("nl").onclick=()=>{$("ovl").innerHTML="";end?(G=null,show("ph")):go(L+1)};$("bk").onclick=()=>{$("ovl").innerHTML="";G=null;show("home")}}
function quit(){clearInterval(tm);G=null;show("home")}
// ---- Daily Ilm: same 10 questions for everyone each day, one per category
function daily(){if(S.dd==today()){toast("Today's Ilm is complete. Return tomorrow.");return}G=null;
let h=0;for(const c of today())h=(h*31+c.charCodeAt(0))|0;const r=()=>(h=Math.imul(h^h>>>15,h|1),h^=h+Math.imul(h^h>>>7,h|61),((h^h>>>14)>>>0)/4294967296);
const sr=(a)=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const ids=dailyIds(sr);
let n=0,lv=3,t=150,done=0;const fin=m=>{if(done)return;done=1;clearInterval(d);$("ovl").innerHTML="";const y=new Date(Date.now()-864e5).toISOString().slice(0,10);S.st=S.last==y?S.st+1:1;S.last=today();S.dd=today();if(lv>0&&n>=ids.length){S.kp+=200}badges();save();if(lv>0&&n>=ids.length)A.say("daily");toast(m+" Streak: "+S.st+(lv>0&&n>=ids.length?" · +200 bonus":""));show("home")};
const d=setInterval(()=>{t--;const e=$("dt");if(e)e.textContent=fmt(Math.max(t,0))+" · "+"♥".repeat(lv);if(t<=0)fin("Time is up.")},1000),nx=()=>{if(done)return;if(n>=ids.length||lv<=0)return fin(lv?"Complete.":"Out of lives.");ask(ids[n++],2,ok=>{if(!ok)lv--;nx()})};nx()}
// ---- Knowledge (what you have answered correctly, with sources) and Profile
function atlas(i){$("ovl").innerHTML=`<div class="ov"><div class="card">${pcard(PLACES[i])}<button class="b p" onclick="$('ovl').innerHTML=''">Close</button></div></div>`}
function know(){show("pf");const L=[...S.learn].reverse();$("pf").innerHTML=`<div class="top"><button onclick="show('home')">‹</button><b>MY KNOWLEDGE ATLAS</b><span></span></div><div class="m">${S.d.length} of ${TOTAL} discovered</div>`+PLACES.slice(0,TOTAL).map((p,i)=>{const u=S.d.includes(p.id);return u?`<button class="b" style="text-align:left" onclick="atlas(${i})">${p.name}<br><span class="m">${p.location} · ${p.category}</span></button>`:`<div class="b" style="opacity:.4;text-align:left">${p.name}<br><span class="m">Complete Level ${i+1} to unlock</span></div>`}).join("")+`<h4>Answers you have learned</h4>`+(L.length?L.map(i=>`<div class="card" style="margin:10px 0"><div class="cat"><span>${CL[Q[i][0]]}</span></div><p><b>${Q[i][3][0]}</b> · ${Q[i][2]}</p><p>${Q[i][4]}</p><p class="m">${Q[i][5]}</p></div>`).join(""):'<p class="m">Correct answers are kept here with their sources.</p>')}
function prof(){show("pf");const f=["quran","hadith","seerah","fiqh","arabic","history"];$("pf").innerHTML=`<div class="top"><button onclick="show('home')">‹</button><b>Profile</b><span></span></div>
<div class="row"><span>Knowledge Points</span><b>${S.kp}</b></div><div class="row"><span>Level</span><b>${plv()}</b></div><div class="row"><span>Questions answered</span><b>${S.a}</b></div><div class="row"><span>Accuracy</span><b>${S.a?Math.round(100*S.c/S.a):0}%</b></div><div class="row"><span>Current streak</span><b>${S.st}</b></div>
${f.map(k=>`<div class="row"><span>${CL[k]}</span><span>${cc(k)} correct</span></div>`).join("")}
<h4>Badges</h4>${BG.map(([n,d])=>`<div class="row" style="opacity:${S.b.includes(n)?1:.4}"><span>${n}</span><span class="m">${d}</span></div>`).join("")}${A.panel()}<button class="b" style="margin-top:16px" onclick="S.m=!S.m;save();prof()">Sound: ${S.m?"off":"on"}</button><button class="b" onclick="rst(this)">Reset progress</button>`}
function rst(b){if(!b.dataset.c){b.dataset.c=1;b.textContent="Tap again to erase all progress";return}try{localStorage.removeItem("ilmq")}catch(e){}location.reload()}
// ---- scenic backgrounds (original flat illustrations) + opening splash
const SCN=[["#f7e8c9","#dcbf8d","#c9a46f","#b78d59","#f3c969","kaaba"],["#fbe6d0","#e3c39a","#d3a977","#bf9360","#f2b86b","plain"],["#d4eaf6","#8cc0a0","#58a67f","#388a65","#f6d27a","mountain"],["#e8f0e4","#9ec9ae","#5fae8a","#2f8f6c","#e7c76a","city"]];
const scene=p=>{const[c0,c1,c2,c3,sn,lm]=SCN[Math.min(p,3)];return`<svg viewBox="0 0 400 800" preserveAspectRatio="xMidYMax slice" style="width:100%;height:100%;display:block" stroke="none"><rect width="400" height="800" fill="${c0}"/><circle cx="310" cy="200" r="42" fill="${sn}" opacity=".85"/><path d="M0 520Q90 470 190 510T400 480V800H0z" fill="${c1}"/><g transform="translate(10 395) scale(1.9)">${SC[lm].replace(/<circle cx="160"[^>]*>/,"")}</g><path d="M0 600Q120 540 220 585T400 560V800H0z" fill="${c2}"/><path d="M0 690Q140 640 260 680T400 660V800H0z" fill="${c3}"/><path d="M160 800Q190 740 235 705" stroke="#fff" stroke-width="10" opacity=".35" fill="none" stroke-linecap="round"/></svg>`};
function splash(){const L=nxt(),p=phOf(L),done=Math.max(0,L-1),pct=Math.round(100*done/TOTAL),d=document.createElement("div");d.id="splash";
d.style.cssText="position:fixed;inset:0;z-index:2000;display:flex;flex-direction:column;justify-content:space-between;color:#1f2d27;transition:opacity .4s";
d.innerHTML=`<div style="position:absolute;inset:0">${scene(p)}</div><div style="position:relative;padding:max(56px,env(safe-area-inset-top)) 28px 0;font-size:26px;font-weight:700;line-height:1.4;max-width:460px">${A.open}</div><div style="position:relative;padding:0 28px calc(28px + env(safe-area-inset-bottom,0px));text-align:center;max-width:520px;width:100%;margin:auto auto 0"><div style="font-size:14px;font-weight:600;margin-bottom:14px">${done?done+" of "+TOTAL+" levels · "+PHASES[p].name:"Your journey begins"}</div><div style="position:relative;height:16px;background:#ffffffb0;border:2px solid #fff;border-radius:10px"><div id="spf" style="height:100%;width:0;background:#0e7a5a;border-radius:8px;transition:width 1.8s ease"></div><div id="spm" style="position:absolute;top:-14px;left:0;width:36px;height:36px;margin-left:-18px;border-radius:9px;background:#fff;border:1px solid #cfe0d6;box-shadow:0 2px 3px #0003;display:grid;place-items:center;transition:left 1.8s ease"><svg viewBox="0 0 48 48" style="width:26px;height:26px"><text x="24" y="35" text-anchor="middle" style="fill:#0e7a5a;font-weight:700" font-size="32" font-family="'Amiri','Noto Naskh Arabic',serif">ع</text></svg></div></div><div style="margin-top:20px;font-weight:700;letter-spacing:5px;color:#0e7a5a">ILM QUEST</div><div style="margin-top:6px;font-size:12px">Tap to continue</div></div>`;
document.body.appendChild(d);requestAnimationFrame(()=>requestAnimationFrame(()=>{$("spf").style.width=pct+"%";$("spm").style.left=pct+"%"}));
let gone=false;const end=()=>{if(gone)return;gone=true;d.style.opacity=0;setTimeout(()=>d.remove(),420)};d.onclick=end;setTimeout(end,3400)}
show("home");splash();try{if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js")}catch(e){}
